name: Email Reminder
on:
  schedule:
    - cron: '30 4 * * 1'  # IST: 5.30 Hr. Format: Min Hr WOM Month DOW
    - cron: '30 4 * * 2'  # * all
    - cron: '30 4 * * 3'  # WOM: Weak of Month, DOW: Day of Weak
    - cron: '30 4 * * 4' 
jobs:
  send-email-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Send email reminder
        run: python ".github/workflows/issue_reminder.py"
