name: Email Reminder
on:
  schedule:
    - cron: '30 4 * * 1'  # Run every Monday at 10:00 AM IST
    - cron: '30 4 * * 2'  # Run every Tuesday at 10:00 AM IST
jobs:
  send-email-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          node-version: '20'
      - name: Send email reminder
        run: python issue_reminder.py
