name: Python Syntax Check

on:
  push:
    branches:
      - main  # Adjust branch name if needed
  pull_request:
    branches:
      - main  # Adjust branch name if needed

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose your Python version
        
      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust as needed
        
      - name: Check Python syntax
        run: python -m py_compile ./*.py
